name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cdp-workflows:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint

# Uncomment this to run the tests in your test suite
#  tests:
#    name: Run Journey Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: DEFRA/cdp-node-journey-test-suite-template/run-journey-tests@0fbf0772fed6bddd2ca9c9722c188b0adf2a2907 # main
